#ifndef VK_ASYNC_COMPUTE_SHADERCOMMON_H
#define VK_ASYNC_COMPUTE_SHADERCOMMON_H

#define WIDTH 2048
#define HEIGHT 2048
#define WORKGROUP_SIZE 32

#define TILE_X 128
#define TILE_Y 128

#endif //VK_ASYNC_COMPUTE_SHADERCOMMON_H
