#ifndef VK_ASYNC_COMPUTE_SHADERCOMMON_H
#define VK_ASYNC_COMPUTE_SHADERCOMMON_H

#define WIDTH 2048
#define HEIGHT 2048
#define WORKGROUP_SIZE 16

#define TILE_X 128
#define TILE_Y 128

#define MANDELBROT_ITERATIONS 256

#endif //VK_ASYNC_COMPUTE_SHADERCOMMON_H
